import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const {PGlite}=await import(process.env.PGLITE_MODULE || '@electric-sql/pglite');
const db=new PGlite();
await db.exec(`
create role anon; create role authenticated; create role service_role;
create table admin_users(user_id uuid primary key,role text);
create table api_tenants(id uuid primary key default gen_random_uuid(),tenant_name text,default_mode text,is_active boolean,beta_access_enabled boolean,metadata jsonb);
create table partner_organizations(id uuid primary key,primary_email text,legal_name text,status text,approved_tenant_id uuid references api_tenants(id),updated_at timestamptz);
create table partner_applications(id uuid primary key,organization_id uuid references partner_organizations(id),status text,entity_details jsonb,decision_summary text,decided_at timestamptz,updated_at timestamptz);
create table partner_application_reviews(id uuid primary key default gen_random_uuid(),application_id uuid references partner_applications(id),reviewer_user_id uuid,decision text,notes text,created_at timestamptz default clock_timestamp());
create table partner_portal_audit_log(id bigserial primary key,organization_id uuid,application_id uuid,actor_user_id uuid,event_type text,metadata jsonb);
insert into admin_users values('00000000-0000-0000-0000-000000000001','ADMIN');
insert into partner_organizations(id,primary_email,legal_name,status) values('00000000-0000-0000-0000-000000000002','partner@example.com','Example Limited','draft');
insert into partner_applications(id,organization_id,status,entity_details) values('00000000-0000-0000-0000-000000000003','00000000-0000-0000-0000-000000000002','draft','{"legal_name":"Example Limited"}');
`);
await db.exec(await readFile(new URL('../supabase/migrations/20260918031000_partner_decision_record.sql',import.meta.url),'utf8'));
const record=async(decision,notes='Notes',actor='00000000-0000-0000-0000-000000000001')=>(await db.query('select record_partner_application_decision($1,$2,$3,$4) as result',['00000000-0000-0000-0000-000000000003',actor,decision,notes])).rows[0].result;
await assert.rejects(record('approved','Notes','00000000-0000-0000-0000-000000000099'),/Super admin/);
await assert.rejects(record('invalid'),/Valid decision/);
const first=await record('approved');const duplicate=await record('approved');
assert.equal(first.review_id,duplicate.review_id);assert.equal(duplicate.reused,true);
assert.equal((await db.query('select count(*)::int as n from partner_application_reviews')).rows[0].n,1);
const tenant=(await db.query('select * from api_tenants')).rows[0];assert.equal(tenant.is_active,false);assert.equal(tenant.default_mode,'sandbox');
for(const state of ['more_information','rejected','suspended'])assert.equal((await record(state)).decision,state);
assert.equal((await db.query('select count(*)::int as n from partner_application_reviews')).rows[0].n,4);
await db.exec(`create function reject_audit() returns trigger language plpgsql as $$begin raise exception 'Audit unavailable'; end;$$; create trigger fail_audit before insert on partner_portal_audit_log for each row execute function reject_audit();`);
await assert.rejects(record('approved','New approval'),/Audit unavailable/);
assert.equal((await db.query('select status from partner_applications')).rows[0].status,'suspended');
assert.equal((await db.query('select status from partner_organizations')).rows[0].status,'suspended');
assert.equal((await db.query('select count(*)::int as n from partner_application_reviews')).rows[0].n,4);
assert.equal((await db.query("select has_function_privilege('authenticated','record_partner_application_decision(uuid,uuid,text,text)','execute') as allowed")).rows[0].allowed,false);
await db.close();console.log('PASS decision transaction: authorization, four states, repeat dedupe, disabled sandbox, audit-failure rollback, restricted RPC grants');
