import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const {PGlite}=await import(process.env.PGLITE_MODULE||'@electric-sql/pglite');
const db=new PGlite();
try {
 await db.exec(`
 create role anon;create role authenticated;create role service_role bypassrls;
 create schema auth;create schema storage;
 create table auth.users(id uuid primary key);create table public.admin_users(user_id uuid primary key,role text);
 create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 grant usage on schema auth to authenticated;
 create table user_profiles(id uuid primary key,account_type text);
 create table bridge_virtual_accounts(id uuid primary key default gen_random_uuid(),user_id uuid,business_user_id uuid,account_details jsonb);
 create table wallets(id uuid primary key default gen_random_uuid(),user_id uuid,currency text,bridge_virtual_account_id text,virtual_account_number text,asset_type text);
 alter table bridge_virtual_accounts enable row level security;alter table wallets enable row level security;
 create policy original_owner on bridge_virtual_accounts for select to authenticated using(auth.uid()=coalesce(business_user_id,user_id));
 create policy original_owner on wallets for select to authenticated using(auth.uid()=user_id);
 grant select on bridge_virtual_accounts,wallets to authenticated;
 create function public.is_borderpay_admin() returns boolean language sql stable security definer as $$select exists(select 1 from admin_users where user_id=auth.uid())$$;
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 `);
 await db.exec(await readFile(new URL('../supabase/migrations/20260920010000_predeposit_evidence_foundation.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../supabase/migrations/20260920020000_predeposit_workflow.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../supabase/migrations/20260920040000_predeposit_instruction_read_boundary.sql',import.meta.url),'utf8'));
 const owner='10000000-0000-4000-8000-000000000001',other='10000000-0000-4000-8000-000000000002';
 await db.query('insert into auth.users values($1),($2)',[owner,other]);
 const add=async(user,no)=>(await db.query("insert into predeposit_invoices(owner_user_id,invoice_number,revision,currency,total_minor,buyer_identity_hash,payload,payload_sha256,policy_version) values($1,$2,1,'GBP',12500,$3,'{}',$3,'borderpay-predeposit-2.4.0') returning id",[user,no,'a'.repeat(64)])).rows[0].id;
 const first=await add(owner,'INV-1');const second=await add(other,'INV-2');
 await assert.rejects(db.query("update predeposit_invoices set total_minor=1 where id=$1",[first]),/immutable/);
 await assert.rejects(db.query("delete from predeposit_invoices where id=$1",[first]),/cannot be deleted/);
 await assert.rejects(db.query("insert into predeposit_documents(invoice_id,owner_user_id,kind,storage_path,sha256,mime_type,size_bytes) values($1,$2,'order_dashboard','bad',$3,'application/pdf',10)",[first,other,'b'.repeat(64)]),/owner/);
 await db.query("insert into predeposit_documents(invoice_id,owner_user_id,kind,storage_path,sha256,mime_type,size_bytes) values($1,$2,'order_dashboard','safe',$3,'application/pdf',10)",[first,owner,'b'.repeat(64)]);
 await assert.rejects(db.query("update predeposit_documents set sha256=$1",['c'.repeat(64)]),/append-only/);
 const claim=(await db.query('select claim_predeposit_invoice($1) x',[first])).rows[0].x;
 assert.equal(claim.status,'screening');assert.ok(claim.lease_id);
 assert.equal((await db.query('select claim_predeposit_invoice($1) x',[first])).rows[0].x,null);
 const assessment={status:'approved',payload_sha256:'a'.repeat(64),policy_version:'borderpay-predeposit-2.4.0',reasons:[]};
 assert.equal((await db.query('select finish_predeposit_screening($1,$2,$3) x',[first,crypto.randomUUID(),assessment])).rows[0].x,false);
 await assert.rejects(db.query('select finish_predeposit_screening($1,$2,$3)',[first,claim.lease_id,{...assessment,payload_sha256:'c'.repeat(64)}]),/does not match/);
 assert.equal((await db.query('select finish_predeposit_screening($1,$2,$3) x',[first,claim.lease_id,assessment])).rows[0].x,true);
 assert.equal((await db.query('select status from predeposit_invoices where id=$1',[first])).rows[0].status,'review_required');
 await assert.rejects(db.query('delete from predeposit_reviews'),/append-only/);
 assert.equal((await db.query('select finish_predeposit_screening($1,$2,$3) x',[first,claim.lease_id,assessment])).rows[0].x,false);
 await db.query("select set_config('request.jwt.claim.sub',$1,false)",[owner]);await db.exec('set role authenticated');
 assert.equal((await db.query('select count(*)::int n from predeposit_invoices')).rows[0].n,1);
 assert.equal((await db.query('select count(*)::int n from predeposit_invoices where id=$1',[second])).rows[0].n,0);
 await assert.rejects(db.query('select claim_predeposit_invoice($1)',[first]),/permission denied/);
 await assert.rejects(db.query("update predeposit_invoices set status='approved'"),/permission denied/);
 await db.exec('reset role');
 assert.equal((await db.query('select mode from predeposit_policy')).rows[0].mode,'disabled');
 assert.equal((await db.query("select public from storage.buckets where id='predeposit-evidence'")).rows[0].public,false);

 const operator='10000000-0000-4000-8000-000000000003';
 await db.query("insert into auth.users values($1)",[operator]);await db.query("insert into admin_users values($1,'COMPLIANCE')",[operator]);
 const draft=(await db.query("insert into predeposit_drafts(owner_user_id,invoice_number) values($1,'DRAFT-1') returning id",[owner])).rows[0].id;
 const asset=(await db.query("insert into predeposit_assets(owner_user_id,kind,storage_path,sha256,mime_type,size_bytes) values($1,'executed_contract','owner/contract',$2,'application/pdf',10) returning *",[owner,'d'.repeat(64)])).rows[0];
 const document={...asset};
 const submit=async(version,currency='EUR',buyerType='company')=>{
  const payload={id:crypto.randomUUID(),revision:version,currency,buyer:{type:buyerType},remitter:{type:'company'}};
  return (await db.query("select submit_predeposit_draft($1,$2,$3,$4,$5,$6,$7,$8,'bridge') x",[owner,draft,version,payload,{total_minor:20000,history:{available:false}},'e'.repeat(64),'f'.repeat(64),[document]])).rows[0].x;
 };
 await assert.rejects(db.query("select submit_predeposit_draft($1,$2,1,'{}','{}',$3,$3,'[]','bridge')",[other,draft,'e'.repeat(64)]),/Draft changed/);
 const snapshot=await submit(1);assert.equal(snapshot.review_context.history.available,true);
 assert.equal((await submit(1)).id,snapshot.id,'repeated submission is idempotent');
 await assert.rejects(db.query("update predeposit_invoices set review_context='{}' where id=$1",[snapshot.id]),/immutable/);
 const claimed=(await db.query("select claim_predeposit_invoice($1) x",[snapshot.id])).rows[0].x;
 const review={status:'approved',payload_sha256:snapshot.payload_sha256,assessed_sha256:'7'.repeat(64),policy_version:snapshot.policy_version,reasons:[]};
 const finish=async(id,lease,actor,decision,assessment=review,path='owner/dossier',sha='6'.repeat(64))=>(await db.query("select complete_predeposit_review($1,$2,$3,$4,$5,$6,$7,'Reviewed evidence and payment details') x",[id,lease,actor,decision,assessment,path,sha])).rows[0].x;
 assert.equal(await finish(snapshot.id,crypto.randomUUID(),null,'approved'),false,'wrong lease cannot approve');
 await assert.rejects(finish(snapshot.id,claimed.lease_id,null,'approved',review,'owner/dossier',null),/dossier/);
 assert.equal(await finish(snapshot.id,claimed.lease_id,null,'approved'),true);
 await db.query("update predeposit_drafts set version=2 where id=$1",[draft]);
 const next=await submit(2);assert.equal((await db.query("select status from predeposit_invoices where id=$1",[snapshot.id])).rows[0].status,'expired');
 const c2=(await db.query("select claim_predeposit_invoice($1) x",[next.id])).rows[0].x;
 await db.query("update predeposit_drafts set version=3 where id=$1",[draft]);const newest=await submit(3,'GBP','individual');
 await assert.rejects(finish(next.id,c2.lease_id,null,'approved'),/newer invoice revision/);
 const c3=(await db.query("select claim_predeposit_invoice($1) x",[newest.id])).rows[0].x;
 await assert.rejects(finish(newest.id,c3.lease_id,null,'approved'),/GBP/);
 assert.equal(await finish(newest.id,c3.lease_id,null,'review_required',{...review,status:'review_required'}),true);
 await assert.rejects(finish(newest.id,null,owner,'approved'),/Compliance operator/);
 await assert.rejects(finish(newest.id,null,operator,'approved'),/GBP/);
 await db.query("insert into predeposit_agreement_templates(version,title,body,status,approved_by,approved_at) values('v1','Terms','Original terms','approved',$1,now())",[operator]);
 await assert.rejects(db.exec("update predeposit_agreement_templates set body='Changed terms' where version='v1'"),/immutable/);
 await db.exec("update predeposit_agreement_templates set status='retired' where version='v1'");
 await db.query("insert into predeposit_evidence_verifications(invoice_id,actor_user_id,patch,rationale) values($1,$2,'{}','Reviewed originals')",[newest.id,operator]);
 await assert.rejects(db.exec("delete from predeposit_evidence_verifications"),/append-only/);
 await db.query("select set_config('request.jwt.claim.sub',$1,false)",[other]);await db.exec("set role authenticated");
 assert.equal((await db.query("select count(*)::int n from predeposit_drafts")).rows[0].n,0);
 assert.equal((await db.query("select count(*)::int n from predeposit_assets")).rows[0].n,0);
 await assert.rejects(db.query("select complete_predeposit_review($1,null,null,'approved','{}',null,null,'bypass')",[newest.id]),/permission denied/);
 await db.exec("reset role");

 await db.query("insert into user_profiles values($1,'business'),($2,'individual')",[owner,other]);
 await db.query("insert into bridge_virtual_accounts(user_id,account_details) values($1,'{\"iban\":\"TEST\"}'),($2,'{\"iban\":\"OTHER\"}')",[owner,other]);
 await db.query("insert into wallets(user_id,currency,asset_type,virtual_account_number) values($1,'USD','fiat_virtual_account','1234'),($1,'USDC','crypto',null)",[owner]);
 await db.query("select set_config('request.jwt.claim.sub',$1,false)",[owner]);await db.exec("set role authenticated");
 assert.equal((await db.query("select count(*)::int n from bridge_virtual_accounts")).rows[0].n,1,'disabled gate preserves owner VA reads');
 await db.exec("reset role;update predeposit_policy set mode='enforce'");
 await db.exec("set role authenticated");
 assert.equal((await db.query("select predeposit_instruction_policy() p")).rows[0].p.required,true);
 assert.equal((await db.query("select count(*)::int n from bridge_virtual_accounts")).rows[0].n,0,'direct VA details hidden under enforcement');
 assert.deepEqual((await db.query("select currency from wallets")).rows.map(r=>r.currency),['USDC'],'fiat coordinates hidden without hiding stablecoin balances');
 await db.query("select set_config('request.jwt.claim.sub',$1,false)",[other]);
 assert.equal((await db.query("select count(*)::int n from bridge_virtual_accounts")).rows[0].n,1,'business-only scope preserves individual reads');
 await db.exec("reset role;update predeposit_policy set mode='disabled'");
 console.log('PASS: mandatory instruction RLS preserves legacy behavior while disabled and blocks direct business bank reads when enforced');

 console.log('PASS: workflow submission, idempotency, revision invalidation, ownership, approval leases, GBP invariant, immutable terms and operator evidence');

 console.log('PASS: private evidence, tenant RLS, immutable snapshots, append-only audit, scoped documents, worker leases, digest binding, no automatic final approval, disabled rollout');

 await db.exec("create schema vault;create schema net;create table vault.decrypted_secrets(name text,decrypted_secret text);create table net.calls(headers jsonb,body jsonb);");
 await db.exec(`create function net.http_post(url text,headers jsonb,body jsonb,timeout_milliseconds integer) returns bigint language plpgsql as $$begin insert into net.calls values(headers,body);return 42;end;$$;`);
 await db.exec(await readFile(new URL('../supabase/migrations/20260920050000_predeposit_worker_dispatch.sql',import.meta.url),'utf8'));
 await db.exec("begin;update predeposit_invoices set status='expired',lease_until=null;");
 assert.equal((await db.query("select invoke_predeposit_worker() id")).rows[0].id,null,'empty queue does not dispatch');
 await db.exec("update predeposit_invoices set status='queued' where id=(select id from predeposit_invoices limit 1)");
 await assert.rejects(()=>db.query("select invoke_predeposit_worker()"),/credential is not configured/);
 await db.exec("rollback");
 await db.exec("insert into vault.decrypted_secrets values('borderpay_predeposit_worker_token','test-only-not-a-real-credential-1234567890')");
 await db.exec("begin;update predeposit_invoices set status='queued',lease_until=null");
 assert.equal((await db.query("select invoke_predeposit_worker() id")).rows[0].id,42);
 assert.equal((await db.query("select count(*)::int n from predeposit_worker_requests")).rows[0].n,1);
 await db.exec("set role authenticated");
 await assert.rejects(()=>db.query("select invoke_predeposit_worker()"),/permission denied/);
 await db.exec("rollback");
 console.log('PASS: durable queue dispatcher requires a server credential and is inaccessible to merchant sessions');

}finally{await db.close();}
