import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const {PGlite}=await import(process.env.PGLITE_MODULE||'@electric-sql/pglite');
const db=new PGlite();
try{
 await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;
 create schema auth;create table auth.users(id uuid primary key);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema auth to authenticated;
 create table public.predeposit_assets(id uuid primary key,owner_user_id uuid,kind text constraint predeposit_assets_kind_check check(kind in ('executed_contract')),mime_type text,sha256 text,scan_status text,verification_status text);
 create table public.predeposit_invoices(status text,lease_until timestamptz);
 create function public.invoke_predeposit_worker() returns bigint language plpgsql as $$begin if not exists(select 1 from public.predeposit_invoices where status='queued') then return null;end if;return 1;end;$$;`);
 await db.exec(await readFile(new URL('../supabase/migrations/20260920210000_predeposit_uploaded_document_checks.sql',import.meta.url),'utf8'));
 const u='00000000-0000-4000-8000-000000000001',v='00000000-0000-4000-8000-000000000002',a='00000000-0000-4000-8000-000000000003',b='00000000-0000-4000-8000-000000000004';
 await db.query('insert into auth.users values($1),($2)',[u,v]);
 await db.query("insert into predeposit_assets values($1,$2,'merchant_invoice','application/pdf',$3,'pending','pending'),($4,$2,'executed_contract','application/pdf',$5,'pending','pending')",[a,u,'a'.repeat(64),b,'b'.repeat(64)]);
 const insert="insert into predeposit_document_checks(owner_user_id,request_id,invoice_asset_id,contract_asset_id,invoice_sha256,contract_sha256,merchant_name,prompt_version) values($1,gen_random_uuid(),$2,$3,$4,$5,'Example Ltd','test') returning id";
 await assert.rejects(()=>db.query(insert,[v,a,b,'a'.repeat(64),'b'.repeat(64)]),/must belong/);
 const id=(await db.query(insert,[u,a,b,'a'.repeat(64),'b'.repeat(64)])).rows[0].id;
 assert.equal((await db.query('select invoke_predeposit_worker() as id')).rows[0].id,1);
 await db.exec("set role authenticated;set request.jwt.claim.sub='"+v+"'");
 assert.equal((await db.query('select * from predeposit_document_checks')).rows.length,0);
 await assert.rejects(()=>db.query('select claim_predeposit_document_check($1)',[id]),/permission denied/);
 await db.exec("set request.jwt.claim.sub='"+u+"'");
 assert.equal((await db.query('select * from predeposit_document_checks')).rows.length,1);
 await assert.rejects(()=>db.query("update predeposit_document_checks set status='matched' where id=$1",[id]),/permission denied/);
 await db.exec('reset role');
 const claim=(await db.query('select claim_predeposit_document_check($1) as r',[id])).rows[0].r;
 assert.equal(claim.status,'reviewing');
 assert.equal((await db.query('select claim_predeposit_document_check($1) as r',[id])).rows[0].r,null);
 await db.query("update predeposit_document_checks set lease_until=now()-interval '1 second' where id=$1",[id]);
 const next=(await db.query('select claim_predeposit_document_check($1) as r',[id])).rows[0].r;
 assert.notEqual(next.lease_id,claim.lease_id);
 assert.equal((await db.query("update predeposit_document_checks set status='matched' where id=$1 and lease_id=$2 returning id",[id,claim.lease_id])).rows.length,0);
 await db.query("update predeposit_document_checks set status='needs_attention',result='{}' where id=$1 and lease_id=$2",[id,next.lease_id]);
 await assert.rejects(()=>db.query("update predeposit_document_checks set status='matched' where id=$1",[id]),/immutable/);
 await assert.rejects(()=>db.query("delete from predeposit_document_checks where id=$1",[id]),/retained/);
 console.log('PASS: document ownership, RLS, service-only claims, leases, immutable results and worker wakeup');
}finally{await db.close();}
