const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const page = await browser.newPage({viewport:{width:1280,height:1000}});
const errors=[]; page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5187/tests/treasury/browser/index.html');
const chart=page.locator('.treasury-volume');
await chart.getByTestId('volume-value').filter({hasText:'10,000.00'}).waitFor();
await chart.getByRole('button',{name:'1W',exact:true}).click();
const slider=chart.getByRole('slider');
await slider.focus(); await page.keyboard.press('Home');
if(!(await chart.getByTestId('volume-value').innerText()).includes('2,500.00'))throw Error('keyboard day value incorrect');
await page.keyboard.press('Enter');
if(await chart.locator('tbody tr').count()!==1)throw Error('day ledger mismatch');
await chart.getByRole('button',{name:'Clear day filter'}).click();
if(await chart.locator('tbody tr').count()!==5)throw Error('period ledger mismatch');
await chart.getByLabel('Volume currency').selectOption('EURC');
if(await chart.locator('tbody tr').count()!==0)throw Error('currency ledger mismatch');
await chart.getByText('No completed EURC transfers in this period.').waitFor();
await chart.getByLabel('Volume currency').selectOption('USDC');
for(const period of ['1M','3M','6M','1Y','1W']){
 await chart.getByRole('button',{name:period,exact:true}).click();
 if(await chart.locator('tbody tr').count()!==5)throw Error('period lost transactions '+period);
}
const box=await slider.boundingBox(); await page.mouse.move(box.x+box.width/3,box.y+box.height/2);
await chart.getByTestId('volume-crosshair').waitFor();
await chart.screenshot({path:'/private/tmp/treasury-volume-desktop.png',style:'.treasury-app-header,.bp-treasury-bottom-nav{visibility:hidden!important}'});
await page.mouse.move(0,0);
await chart.getByRole('button',{name:'Hide 5 transactions'}).click();
await page.evaluate(()=>window.partialHistory=true);
await page.getByRole('button',{name:'Refresh treasury data',exact:true}).click();
await chart.getByText('Partial history — totals include loaded records only.').waitFor();
const mobile = await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
const phone=await mobile.newPage(); await phone.goto('http://127.0.0.1:5187/tests/treasury/browser/index.html');
const phoneChart=phone.locator('.treasury-volume');
await phoneChart.getByRole('button',{name:'1W',exact:true}).tap();
await phoneChart.getByRole('slider').scrollIntoViewIfNeeded();
const touchBox=await phoneChart.getByRole('slider').boundingBox();
await phone.touchscreen.tap(touchBox.x+2,touchBox.y+50);
await phoneChart.getByTestId('volume-crosshair').waitFor();
if(await phoneChart.locator('tbody tr').count()!==1)throw Error('touch selection did not filter ledger');
await phoneChart.screenshot({path:'/private/tmp/treasury-volume-mobile.png',style:'.treasury-app-header,.bp-treasury-bottom-nav{visibility:hidden!important}'});
await phoneChart.getByRole('button',{name:'Clear day filter'}).tap();
await phoneChart.getByRole('button',{name:'Hide 5 transactions'}).tap();
await phoneChart.screenshot({path:'/private/tmp/treasury-volume-mobile-overview.png',style:'.treasury-app-header,.bp-treasury-bottom-nav{visibility:hidden!important}'});
await phone.setViewportSize({width:320,height:740});
if(await phone.evaluate(()=>document.querySelector('.bp-treasury-shell').scrollWidth>innerWidth))throw Error('chart overflow at 320px');
if(errors.length)throw Error(errors.join('\n'));
console.log('PASS chart total, 5 periods, currency isolation, keyboard/crosshair, day and period ledgers, partial-history notice, native touch selection, 320px layout');
await browser.close();
