const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const page = await browser.newPage({viewport:{width:1280,height:1000}});
const errors=[]; page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5187/tests/treasury/browser/index.html');
const chart=page.locator('.treasury-volume');
await chart.getByText('Show your balance to view its history.').waitFor();
if(await chart.getByRole('slider').count())throw Error('hidden balance chart leaks values');
await page.getByRole('button',{name:'Show treasury balance',exact:true}).click();
await chart.getByTestId('volume-value').filter({hasText:'140,939.90'}).waitFor();
await page.locator('.treasury-total').filter({hasText:'140,939.90'}).waitFor();
if(await chart.locator('select').count())throw Error('currency selector remains');
await chart.getByRole('button',{name:'1W',exact:true}).click();
const slider=chart.getByRole('slider');
await slider.focus(); await page.keyboard.press('Home');
if(!(await chart.getByTestId('volume-caption').innerText()).includes('100,000.00'))throw Error('keyboard historical balance incorrect');
if(!(await chart.getByTestId('volume-value').innerText()).includes('140,939.90'))throw Error('hover changed current total');
if(await chart.locator('table').count())throw Error('Home duplicates Activity ledger');
for(const period of ['1M','3M','6M','1Y','1W'])await chart.getByRole('button',{name:period,exact:true}).click();
const box=await slider.boundingBox(); await page.mouse.move(box.x+box.width/3,box.y+box.height/2);
await chart.getByTestId('volume-crosshair').waitFor();
await chart.screenshot({path:'/private/tmp/treasury-usd-desktop.png',style:'.treasury-app-header,.bp-treasury-bottom-nav{visibility:hidden!important}'});
await page.getByRole('navigation',{name:'Treasury navigation',exact:true}).getByRole('button',{name:'Activity',exact:true}).click();
if(await page.locator('.treasury-volume').count())throw Error('Activity duplicates Home chart');
await page.getByRole('navigation',{name:'Treasury navigation',exact:true}).getByRole('button',{name:'Receive',exact:true}).click();
for(const name of ['United States dollar flag','Euro flag','British pound flag'])await page.getByRole('img',{name,exact:true}).waitFor();
await page.getByRole('navigation',{name:'Treasury navigation',exact:true}).getByRole('button',{name:'Home',exact:true}).click();
await page.evaluate(()=>window.partialHistory=true);
await page.getByRole('button',{name:'Refresh treasury data',exact:true}).click();
await chart.getByText('Balance history is temporarily unavailable.').waitFor();
await chart.getByTestId('volume-value').filter({hasText:'140,939.90'}).waitFor();
const mobile = await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
const phone=await mobile.newPage(); await phone.goto('http://127.0.0.1:5187/tests/treasury/browser/index.html');
await phone.getByRole('button',{name:'Show treasury balance',exact:true}).tap();
const phoneChart=phone.locator('.treasury-volume');
await phoneChart.getByRole('button',{name:'1W',exact:true}).tap();
await phoneChart.getByRole('slider').scrollIntoViewIfNeeded();
const touchBox=await phoneChart.getByRole('slider').boundingBox();
await phone.touchscreen.tap(touchBox.x+2,touchBox.y+50);
await phoneChart.getByTestId('volume-crosshair').waitFor();
await phoneChart.screenshot({path:'/private/tmp/treasury-usd-mobile.png',style:'.treasury-app-header,.bp-treasury-bottom-nav{visibility:hidden!important}'});
await phone.setViewportSize({width:320,height:740});
if(await phone.evaluate(()=>document.querySelector('.bp-treasury-shell').scrollWidth>innerWidth))throw Error('chart overflow at 320px');
if(errors.length)throw Error(errors.join('\n'));
console.log('PASS USD total parity, balance privacy, five periods, keyboard/touch, separate Activity, flags, incomplete history, 320px layout');
await browser.close();
