const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1050}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5187/tests/treasury/browser/index.html');
await page.getByRole('button',{name:'Show treasury balance',exact:true}).click();
await page.screenshot({path:`${process.env.TREASURY_SCREENSHOTS || '/tmp'}/treasury-desktop.png`,fullPage:true});
await page.getByRole('navigation',{name:'Treasury navigation',exact:true}).getByRole('button',{name:'Receive',exact:true}).click();
await page.getByText('04-00-75',{exact:true}).waitFor();
await page.screenshot({path:`${process.env.TREASURY_SCREENSHOTS || '/tmp'}/treasury-accounts.png`,fullPage:true});
await page.getByRole('button',{name:'Copy Sort code',exact:true}).click();
await page.getByRole('navigation',{name:'Treasury navigation',exact:true}).getByRole('button',{name:'Activity',exact:true}).click();
await page.getByLabel('Search treasury activity').fill('fixture-transfer-1');
if(await page.locator('tbody tr').count()!==1)throw Error('activity search');
await page.getByLabel('Search treasury activity').fill('');
await page.getByLabel('Filter activity status').selectOption('pending');
if(await page.locator('tbody tr').count()!==1)throw Error('pending excludes refunded');
await page.getByRole('navigation',{name:'Treasury navigation',exact:true}).getByRole('button',{name:'Send',exact:true}).click();
await page.getByLabel('Source asset').selectOption('base:USDC');
await page.getByLabel('Amount',{exact:true}).fill('999999');
await page.getByLabel(/Destination address/).fill('0x0000000000000000000000000000000000000001');
if(await page.getByRole('button',{name:'Review transfer'}).isEnabled())throw Error('overspend enabled');
await page.getByLabel('Amount',{exact:true}).fill('12');
await page.getByRole('button',{name:'Review transfer'}).click();
await page.getByLabel('PIN',{exact:true}).fill('1234');
await page.getByRole('button',{name:'Confirm transfer'}).click();
await page.getByText('Transfer submitted',{exact:true}).waitFor();
if(await page.evaluate(()=>window.sends)!==1)throw Error('duplicate send');
await page.getByRole('navigation',{name:'Treasury navigation',exact:true}).getByRole('button',{name:'Home',exact:true}).click();
await page.evaluate(()=>{window.failRead=true;window.readDelay=100;});
await page.getByRole('button',{name:'Refresh treasury data',exact:true}).click();
await page.getByText('Fixture refresh unavailable',{exact:true}).waitFor();
await page.locator('.treasury-total').filter({hasText:'140,939.90'}).waitFor();
await page.evaluate(()=>window.failRead=false);
await page.getByRole('button',{name:'Try again',exact:true}).click();
await page.getByText('Fixture refresh unavailable',{exact:true}).waitFor({state:'hidden'});
await page.locator('[data-sonner-toast]').waitFor({state:'hidden',timeout:10000});
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:`${process.env.TREASURY_SCREENSHOTS || '/tmp'}/treasury-mobile.png`,fullPage:true});
for(const view of ['Wallet','Receive','Activity','Send','Home']){
 await page.getByRole('navigation',{name:'Mobile treasury navigation',exact:true}).getByRole('button',{name:view,exact:true}).click();
 const overflow=await page.evaluate(()=>document.querySelector('.bp-treasury-shell').scrollWidth>innerWidth);
 if(overflow)throw Error('overflow '+view);
}
await page.getByRole('button',{name:'Open treasury menu',exact:true}).click();
await page.getByRole('dialog').waitFor();
await page.keyboard.press('Escape');
await page.getByRole('dialog').waitFor({state:'hidden'});
await page.getByRole('button',{name:'Open treasury menu',exact:true}).click();
await page.getByRole('navigation',{name:'Treasury menu navigation',exact:true}).getByRole('button',{name:'Receive',exact:true}).click();
await page.getByRole('dialog').waitFor({state:'hidden'});
await page.getByText('04-00-75',{exact:true}).waitFor();
await page.getByRole('button',{name:'Back to treasury home',exact:true}).click();
await page.setViewportSize({width:320,height:740});
if(await page.evaluate(()=>document.querySelector('.bp-treasury-shell').scrollWidth>innerWidth))throw Error('320px overflow');
if(errors.length)throw Error(errors.join('\n'));
console.log('PASS desktop/mobile navigation, sort code, search, pending status, balance limit, one-time fixture send, stale refresh recovery, 320px layout; no browser errors');
await browser.close();
