#!/usr/bin/env python3
"""
Compute RC1 certification status from deployment-blocking evidence audits.

RC1 is PASS only when all required RC1 gate audits pass.
Otherwise status is OPEN.
"""
from __future__ import annotations

import argparse
import datetime as dt
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "utils" / "generated" / "rc1Status.ts"

AUDITS = [
    "tests/audit/rc1_business_certification_gate_audit.py",
    "tests/audit/rc1_runtime_killswitch_audit.py",
    "tests/audit/operator_account_exclusion_audit.py",
]


def run(cmd: list[str]) -> tuple[int, str, str]:
    p = subprocess.run(
        cmd,
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    return p.returncode, p.stdout.strip(), p.stderr.strip()


def compute_status() -> tuple[str, list[str]]:
    failures: list[str] = []
    for audit in AUDITS:
        rc, out, err = run(["python3", audit])
        if rc != 0:
            tail = "\n".join((out or err).splitlines()[-8:])
            failures.append(f"{audit}\n{tail}")
    return ("PASS" if not failures else "OPEN", failures)


def render(status: str) -> str:
    now = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    return (
        "/**\n"
        " * Auto-generated by scripts/ci/compute_rc1_status.py\n"
        " * Do not edit manually.\n"
        " */\n\n"
        "export type RC1CertificationStatus = 'OPEN' | 'PASS';\n"
        f"export const RC1_CERTIFICATION_STATUS: RC1CertificationStatus = '{status}';\n"
        "export const RC1_STATUS_SOURCE = 'computed';\n"
        f"export const RC1_STATUS_COMPUTED_AT = '{now}';\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Compute RC1 certification status from audits.")
    parser.add_argument("--write", action="store_true", help="Write computed status file.")
    parser.add_argument("--check", action="store_true", help="Fail if committed status file does not match computed status.")
    parser.add_argument(
        "--require-pass",
        action="store_true",
        help="Fail unless both computed and committed RC1 status are valid and PASS.",
    )
    args = parser.parse_args()
    if args.require_pass and (args.write or args.check):
        parser.error("--require-pass cannot be combined with --write or --check")

    status, failures = compute_status()
    desired = render(status)

    if args.write:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(desired, encoding="utf-8")
        print(f"[rc1-status] wrote {OUT.relative_to(ROOT)} status={status}")
        if failures:
            print("[rc1-status] audits failing; status forced OPEN")
        return 0

    current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
    m = re.search(r"RC1_CERTIFICATION_STATUS:\s*RC1CertificationStatus\s*=\s*'(OPEN|PASS)'", current)
    current_status = m.group(1) if m else None
    matches = current_status == status

    if args.require_pass:
        if status != "PASS":
            print(f"[rc1-status] FAIL: computed status must be PASS, got {status}")
            if failures:
                print("[rc1-status] gate failures:")
                for failure in failures:
                    print("---")
                    print(failure)
            return 1
        if current_status != "PASS":
            print(
                "[rc1-status] FAIL: committed generated status must be valid and PASS, "
                f"got {current_status or 'missing/invalid'}"
            )
            return 1
        if not matches:
            print("[rc1-status] FAIL: committed generated status does not match computed PASS")
            return 1
        print("[rc1-status] PASS: computed and committed generated status are PASS")
        return 0

    if args.check:
        if not matches:
            print("[rc1-status] FAIL: computed status differs from committed generated file")
            print(f"[rc1-status] expected status={status}")
            print(f"[rc1-status] current status={current_status or 'missing'}")
            print("[rc1-status] run: python3 scripts/ci/compute_rc1_status.py --write")
            return 1
        print(f"[rc1-status] PASS: committed status matches computed status={status}")
        return 0

    print(f"[rc1-status] computed status={status}")
    if failures:
        print("[rc1-status] gate failures:")
        for f in failures:
            print("---")
            print(f)
    return 0


if __name__ == "__main__":
    sys.exit(main())
