export type ReceiptPdfLine = { label?: string; value: string; large?: boolean };

function pdfText(value: unknown) {
  return String(value ?? '')
    .normalize('NFKD')
    .replace(/[^\x20-\x7E]/g, '-')
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)')
    .replace(/[\r\n]+/g, ' ')
    .trim();
}

function approximateWidth(value: string, fontSize: number) {
  return Math.min(330, value.length * fontSize * 0.52);
}

export function buildReceiptPdf(lines: ReceiptPdfLine[]) {
  const headline = lines.find((line) => line.large) || lines[0];
  const details = lines.filter((line) => line !== headline);
  const content: string[] = [
    '0.05 0.07 0.09 rg',
    'BT /F2 16 Tf 56 744 Td (BorderPay) Tj ET',
    '0.38 0.41 0.45 rg',
    `BT /F1 10 Tf 56 710 Td (${pdfText(headline?.label || 'Money out receipt')}) Tj ET`,
    '0.05 0.07 0.09 rg',
    `BT /F2 18 Tf 56 680 Td (${pdfText(headline?.value || '')}) Tj ET`,
    '0.82 0.84 0.86 RG 0.8 w 56 652 m 556 652 l S',
  ];

  let y = 620;
  details.forEach((line) => {
    const label = pdfText(line.label || '');
    const value = pdfText(line.value);
    const fontSize = 10;
    if (value.length > 65) {
      const words = value.split(' ');
      const wrapped = ['', ''];
      words.forEach((word) => {
        const target = wrapped[0].length < 58 ? 0 : 1;
        wrapped[target] = `${wrapped[target]} ${word}`.trim();
      });
      content.push('0.38 0.41 0.45 rg');
      content.push(`BT /F1 9 Tf 56 ${y} Td (${label}) Tj ET`);
      content.push('0.05 0.07 0.09 rg');
      content.push(`BT /F1 9 Tf 56 ${y - 14} Td (${pdfText(wrapped[0])}) Tj ET`);
      if (wrapped[1]) content.push(`BT /F1 9 Tf 56 ${y - 27} Td (${pdfText(wrapped[1])}) Tj ET`);
      content.push(`0.92 0.93 0.94 RG 0.5 w 56 ${y - 40} m 556 ${y - 40} l S`);
      y -= 58;
      return;
    }
    const valueX = Math.max(222, 556 - approximateWidth(value, fontSize));
    content.push('0.38 0.41 0.45 rg');
    content.push(`BT /F1 9 Tf 56 ${y} Td (${label}) Tj ET`);
    content.push('0.05 0.07 0.09 rg');
    content.push(`BT /F1 ${fontSize} Tf ${valueX.toFixed(1)} ${y} Td (${value}) Tj ET`);
    content.push(`0.92 0.93 0.94 RG 0.5 w 56 ${y - 16} m 556 ${y - 16} l S`);
    y -= 38;
  });

  content.push('0.38 0.41 0.45 rg');
  content.push('BT /F1 8 Tf 56 54 Td (Generated by BorderPay - Keep this receipt for your records.) Tj ET');

  const stream = content.join('\n');
  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>',
    `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,
  ];
  let pdf = '%PDF-1.4\n';
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(pdf.length);
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });
  const xrefStart = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  offsets.slice(1).forEach((offset) => {
    pdf += `${String(offset).padStart(10, '0')} 00000 n \n`;
  });
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;
  return new Blob([pdf], { type: 'application/pdf' });
}
